### ISSUE TITLE
ミートアップの運営方法を考える

### ISSUE THREAD

**Issue by satococoa** [yurufuwa/meetups#1]
- [x] 募集〜告知〜締め切り
- [x] 成果発表〜KPT

**Comment by satococoa** [comment]
いったん、 #p4d の月2回体制を引き継ぐ。
月の初めに万葉さん、半ばにイグニス。

主催の誰かはミートアップに出られるようにする。

**Comment by satococoa** [comment]
とりあえず各回ごとに issue を立てる形式でやってみる

**Comment by willnet** [comment]
第一回ミートアップは今月やります？それとも9月からのほうがいいですかね

**Comment by satococoa** [comment]
8/21イグニスと9/4万葉で既に場所が確保済みです！

**Comment by willnet** [comment]
:+1:
