### ISSUE TITLE
第19回 meetup 2015-02-19(Thu) 19:30 〜 @部室

### ISSUE THREAD

**Issue by ginkouno** [yurufuwa/meetups#21]
日時: 2015-02-19(Thu) 19:30 〜 21:30
会場: [ゆるデ部室](http://10mado.jp/#map)
定員: 8名
参加費: なし (おやつやおつまみなどは歓迎 :beers: )
## 参加方法

この issue に以下の内容でコメントつけてください。
もしご都合が悪くなってしまった場合はその旨追記お願いします。
繰り上がりリマインダ等は送りませんので各自でご確認ください。
- 名前
- 当日やりたいこと
- 何か一言
## 当日の流れ
- 19:30〜19:45 ゆるゆるっと集合
- 19:45〜 自己紹介とやりたいことを発表
- 20:00〜 ゆるふわに開発
- 21:15〜 成果発表、初めての人に感想を言っていただく、KPT、次回の日付決める
- 21:30〜 片付け
- 22:00 作業する人以外は解散(もしくは外でごはん)の方向で( ˘ω˘)"

[Googleマップ](https://www.google.co.jp/maps/place/%E3%80%92150-0002+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E6%B8%8B%E8%B0%B7%EF%BC%93%E4%B8%81%E7%9B%AE%EF%BC%91%E2%88%92%EF%BC%91%EF%BC%95+%E3%82%BE%E3%83%B3%E3%83%8D%E3%83%B3%E3%83%8F%E3%82%A4%E3%83%A0%E6%B8%8B%E8%B0%B7/@35.6577886,139.7073307,17z/data=!3m1!4b1!4m2!3m1!1s0x60188b5c1d8d49d1:0x5e5e588f9d498bf5)

迷った場合などは海老沢 (@satococoa) or 前島 (@willnet) までご連絡ください。
(#yurudev タグつけて @satococoa or @willnet へメンション)
## 持ち物
- 名札 (ある方)
- PC
  @all

**Comment by willnet** [comment]
- @willnet / まえしま
- https://savanna.io
- たぶん参加できるはず

**Comment by ginkouno** [comment]
- @ginkouno / こうの
- ランチ決めるサービスの続き
- :beers:

**Comment by umegaya** [comment]
- @umegaya / いやとみ
- luact: gossip protocolからのnode追加通知を受けての動的なraft consensus groupの作成
- 三度目の正直

**Comment by machida** [comment]
- @machida / まちだ
- kulku（道案内サービス）
- 頑張ります

**Comment by hiroy** [comment]
- やまおか
- チームのタスク管理できるやつ
- お仕事は終わらせておきたい ( ˘ω˘)

**Comment by ta1kt0me** [comment]
- @ta1kt0me/ とみー
- 仕事のソースか何かGemのソース読むとか写経とか
- 初参加です。前回行けなかったので今日こそ。よろしくお願いします。

**Comment by fukayatsu** [comment]
- @fukayatsu / ふかやつ
- esaもしくはesa以外の何か
- ﾅﾏﾊﾑ "(\( ⁰⊖⁰)/)"

**Comment by y-yagi** [comment]
- @y-yagi / やぎぬま
- 旅行予定管理のサービスやります
- 初参加です。 よろしくお願いします。

**Comment by willnet** [comment]
- メッセージ送る機能の開発
- 送るのはできたが表示で悩んでた
  - アドバイスもらえて助かりました (( ⁰⊖⁰)/)

**Comment by ginkouno** [comment]
- 住所の表示 -> 中心にマーカー表示 -> 保存ボタンでajax request -> controllerで受け取ってmodelに保存 までできた
- loadのタイミング的に問題があるようで、初回ページ表示時に、js script的にGmap objectがまだ読み込まれてねーよと怒られることがある
  - document.readyの後でもだめみたい。どーすべ

**Comment by fukayatsu** [comment]
- [release_note/2015/02/19/記事更新時のnotificationにdiffへのリンクを追加しました - docs.esa.io](https://docs.esa.io/posts/66)
- 生ハムを準備しました
  - ![img_20150219_211420](https://cloud.githubusercontent.com/assets/1041857/6266403/abec7446-b87c-11e4-8def-42bec20da88b.jpg)

**Comment by ta1kt0me** [comment]
- localのvagrantでcapistrano試すことにしました
  - そうとしたらboxの中にgitもruby入っていなかったので ansible に挑戦
  - git 入れるところまでいきました
  - 最初はchef入れようとしたらまごついてしまったのでansibleにしました

**Comment by hiroy** [comment]
- HerokuでPHPでworkerのテスト https://github.com/hiroy/php-worker-test
- workerとりあえず動かせるライブラリ作り途中 https://github.com/hiroy/clover-worker
- Slackの通知デザインむずかしい

![2015-02-19 21 18 24](https://cloud.githubusercontent.com/assets/21510/6266415/dd056e48-b87c-11e4-9121-f12b05a46e22.png)

**Comment by y-yagi** [comment]
- elasticsearchを利用しての検索機能の開発
  - elasticsearch-railsに入ってる[サンプル](https://github.com/elasticsearch/elasticsearch-rails/blob/master/elasticsearch-rails%2Flib%2Frails%2Ftemplates%2Fsearchable.rb)読んでた
- 簡単な検索は出来るようになった
- テストがまだ
  - [Test::Cluster](https://github.com/elasticsearch/elasticsearch-ruby/blob/master/elasticsearch-extensions/README.md#testcluster)というのがあるらしい?

**Comment by umegaya** [comment]
- gossip protocolで受け取ったnode情報を使ってraft consensus groupを生成できるようになりました。
- 最初に想定していた実装だとすべてのnodeがuser_stateとしてgossipでroot_range情報を通信するので通信量がもったいないので、root_rangeのraft leaderのスレッドだけが定期的にroot_rangeをgossipするように修正中

**Comment by machida** [comment]
ボタンの見た目を変えました。

![image](https://cloud.githubusercontent.com/assets/168265/6266448/58aa3664-b87d-11e4-8f8f-260a613d3cfb.png)

mixinにしました。

あと、helpのバルーンなどを作ってたのですが、成果発表のタイミングで出なくなった。

**Comment by willnet** [comment]
# 初参加の方から一言
- 静かなところでもくもく作業できて集中できた
- 前にドタキャンしてしまったので今回これてよかった。また来たい！

# KPT

## Keep
- 仕事をしなかった
- 席増えた
- 生ハム2号
- 相談で課題が解決した
- 機能リリースした！
- 捗った

## Problem
- 新南口から来ると差し入れにこまる
  - ローソン差し入れ用のお菓子が少ない

## Try
- ( ˘ω˘)
