### ISSUE TITLE
3月のミータップ

### ISSUE THREAD

**Issue by willnet** [yurufuwa/meetups#23]
ぼくが3月の中旬〜下旬くらいまでとても忙しくなりそうなので、代役を募集します＞＜

**Comment by fukayatsu** [comment]
やります〜

**Comment by willnet** [comment]
![gracias.jpeg (599×426)](http://hana.bi/wp-content/uploads/2014/04/gracias.jpeg)

**Comment by hiroy** [comment]
@fukayatsu ++ :+1:

**Comment by willnet** [comment]
:+1:

**Comment by satococoa** [comment]
@fukayatsu ++

**Comment by taea** [comment]
@fukayatsu ありがとー "(\( ⁰⊖⁰)/)"

**Comment by ginkouno** [comment]
@fukayatsu
![suge-iine](https://cloud.githubusercontent.com/assets/18394/6407855/3f65dd10-be8c-11e4-9247-042c423f3578.png)
