### ISSUE TITLE
第28回 meetup 2015-05-02~2015-05-06 @島根

### ISSUE THREAD

**Issue by willnet** [yurufuwa/meetups#31]
いつものミートアップのようにやることを宣言して、4日の夕食後あたりで成果発表します=͟͟͞͞ (\( ⁰⊖⁰)/)

あとは景色の写真などを適当に貼り付けて、これなかった人たちを羨ましがらせましょう( ˘ω˘)"

**Comment by fukayatsu** [comment]
- fukayatsu
- APIの準備を進める
- (\( ⁰⊖⁰)/)

**Comment by willnet** [comment]
- willnet
- ごはんレコメンドサービスのクローズドベータ版を作る
- 初島根=͟͟͞͞ (\( ⁰⊖⁰)/)

**Comment by ir3** [comment]
:white_square_button: iR3

:one: 刻言道場「まいトレ」の新版の実装を進める

:u7981:(( ⁰⊖⁰)/)

**Comment by hokkai7go** [comment]
東京からこんにちは。
@willnet さん、ごはんレコメンドサービスがすごく気になるので、今度お話聞かせてください！ :rice: :rice_ball: :ear_of_rice:

**Comment by willnet** [comment]
@hokkai7go :ok_woman:

**Comment by taea** [comment]
- ken_c_lo
- iOS + swift の勉強とか esaとか
- (\( ˘⊖˘)/)

**Comment by tatsuosakurai** [comment]
- tatsuoSakurai
- なんかアプリ作る。ネタ出し中 -> 良いネタ思いつかなかったんで、既存アプリのリファクタしようと思います！
- 島根の人親切だなあ

**Comment by ginkouno** [comment]
- ginkouno
- ごはんレコメンドサービスのクローズドベータ版を作る
- 海だー

**Comment by willnet** [comment]
![img_3802](https://cloud.githubusercontent.com/assets/82371/7443304/8dbb0158-f17b-11e4-8d4c-d875cb775cbd.JPG)

**Comment by willnet** [comment]
> ウミウシはアメフラシと比べて小さく、じっくり探さないと見つからないかもしれません。

でかいのは基本アメフラシと考えて良さそう

[アメフラシとウミウシ[せとうちネット]](https://www.env.go.jp/water/heisa/heisa_net/setouchiNet/seto/setonaikai/taikenikimono1-1.html)

**Comment by willnet** [comment]
![img_3824](https://cloud.githubusercontent.com/assets/82371/7443712/785c3d48-f19b-11e4-847b-3acaf79464e9.JPG)

**Comment by willnet** [comment]
# ここから成果発表

**Comment by willnet** [comment]
## やった
- ご飯レコメンドサービス
- 直近作るものと方向性について @ginkouno さんと認識を合わせた
- ユーザ登録系を作っている
  - facebookログイン→味の好みを入力
  - 拠点となる地点を設定
  - オススメをメールする時間を設定する画面(wip)
  - メアド登録機能の実装をサボりたくてtwitterログインを削除して工数を短縮した

## これからやりたいこと
- オススメを表示する画面
- オススメをメールする機能
- 管理画面

## 所感

この辺の写真の構図、よい

![img_3865](https://cloud.githubusercontent.com/assets/82371/7454829/7e89fb48-f2b2-11e4-97f7-143cd2f28d05.JPG)

**Comment by ginkouno** [comment]
### やったこと
- ランチレコメンドサービスの開発

### 実績
- @willnet さんと 打ち合わせ
- Heroku周り
  - ドメイン取得
  - DNS周りの設定
  - 該当ドメイン admin@menure.co メールアドレスの取得
  - SSL証明書取得
- データの準備
  - 手元の店舗データのcsvへの吐き出し
  - 手元の店舗データとぐるなび情報との紐付け(ぐるなびAPIで検索)
  - 目視でデータの分類 <- now!

### 今後の作業
- データの分類続き
  - カテゴリとか分けた方がいいのか再度考えたい
  - 0 / 1のどちらかになっているので、5段階数値を各好み値に対しつけた方がいいのか考える

**Comment by fukayatsu** [comment]
![screen shot 2015-05-04 at 11 20 05 pm](https://cloud.githubusercontent.com/assets/1041857/7455078/2f10d2ba-f2b4-11e4-9bb5-6a808455e442.png)
- [x] esa/esareaで番号付きリストの入力補助の追加
  - [release_note/2015/05/03/番号付きリストの入力補助に対応しました - docs.esa.io](https://docs.esa.io/posts/99)
- [x] esa ユーザサポート
- [x] esa api/v1に向けたリファクタリング
- [x] esa api/v1の実装
  - [x] personal access token発行機能: w/ @taea 
  - [x] 記事API: [:index, :show, :create, :update, :destroy]
  - [x] チームAPI: [:index, :show]
  - [x] Add request specs for API
  - [x] rate limit
  - [ ] apiサーバ分離

### 検討中
- APIで記事カテゴリやタグを変更する場合にname=`foo/bar/baz #tag1`とするかそれともcategory=`foo/bar`, name=`baz`, tags=`[tag1]`のように分けるか

**Comment by taea** [comment]
### 進捗状況
- 2日目前半はesa対応
- 2日目後半から iOS + swiftの勉強
- これやってる( :fried_shrimp: ちゃんおすすめ) [たのしいアプリプログラミング 〜 Swiftで始めよう！ on the App Store on iTunes](https://itunes.apple.com/jp/app/tanoshiiapuripuroguramingu/id941389582?l=en&mt=8)
- RSSをパースするところまでやった
- エラーの解決方法がわからなかったりXcodeの使い方がわからなかったりしてハマっている時間がとにかく長くてつらかった
- SIGABRT エラー意味わからんつらい

### 成果物イメージ
- [![](https://img.esa.io/uploads/production/attachments/25/2015/05/04/2/52d54751-4b98-46e0-8e34-1a7d46353035.png)](https://img.esa.io/uploads/production/attachments/25/2015/05/04/2/52d54751-4b98-46e0-8e34-1a7d46353035.png)
- ![2015-05-04 17 23 18](https://cloud.githubusercontent.com/assets/341101/7454767/dd855cd8-f2b1-11e4-8f3e-6c2aff8165a1.png)

### これから
- とりあえず1冊終わらせたい
- 1冊終わらせると簡単なRSSとかAPIのViewerが作れるっぽいので、既存のフィードを使った、作り方は簡単だけど割と面白いアプリのアイデアないかなーとか考えてる

### 反省点
- わりとねむかった
- つらい基礎の勉強部分は東京で終わらしておくんだったなあ…
- 美保関最高にいい

**Comment by ir3** [comment]
:one: 刻言道場「まいトレ」の新版の実装を進めました。
- 旧版 http://maitore.net 
  (Ramaze/PostgreSQL http://www.slideshare.net/FUKUIOsamu/20101106-ramaze )
  → 新版途上 http://maitore.ruby.iijgio.com/ (Rails4/MySQL)
- PostgreSQL にて蓄積したDBデータを MySQLに移行する
  dumpファイルを手編集して、レコード毎にPaas上で db:seed で登録するプログラムを書いてデータとプログラムを git push後 クラウド上で復元
- 実行環境
  　さくらインターネット → IIJ MOGOK
- 今後
  見栄え回りの整備

**Comment by tatsuosakurai** [comment]
- アプリ考えてたけどネタ出しで時間切れ -> 既存アプリの改修
- 歴史あるアプリのだいぶ溜まった bundle update PR の続き
- DB drop 後に落ちる -> Factory に id 固定されてたり、DatabaseRewinder の except が上手く動かせてなかったりでドハマりしてた。
- DatabaseRewinder の挙動を追ったりしてたけど、結局よくわからず、設定の方法を変えた
- rails-erd 入れたり rake stats したり
- ざっくり全体のコードを見渡してリファクタポイントをまとめてた

## メモ
- やること東京で決めてくればよかった…手をガシガシ動かせるようにしたかった
- 時間決めてピボットしたのはよかった
- 歴史ある既存アプリ、作りなおすのがいいのかなあ‥しかし今までのデータもあるしのう…
- 美保関よかった

**Comment by willnet** [comment]
合宿最高だったのでまたやりたい=͟͟͞͞ (\( ⁰⊖⁰)/)
