### ISSUE TITLE
ゆるふわダッシュボーダーズ新年会

### ISSUE THREAD

**Issue by willnet** [yurufuwa/meetups#59]
ゆるダボ参加者の新年会です。

詳細は後で書きます
- 日時: 2016-01-22(Fri) 19:30 〜
- 会場: 渋谷のどこか

**Comment by willnet** [comment]
@all ゆるダボな方たち

参加人数を把握したいので、参加希望の方 1月8日(金)一杯までにコメントください＞＜

**Comment by ginkouno** [comment]
参加します！

**Comment by willnet** [comment]
٩(๑❛ᴗ❛๑)۶

**Comment by machida** [comment]
連絡遅れてすいません！参加しますー
みんなに連絡しておきます

**Comment by champierre** [comment]
参加します！

**Comment by bluerabbit** [comment]
初めて参加します。

**Comment by is8r** [comment]
参加します〜

**Comment by taea** [comment]
遅くなってすみませんm(__)m 今回パスします〜

**Comment by ir3** [comment]
すみません。パスします m(_ _)m

**Comment by willnet** [comment]
@machida さん連絡ありがとうございますー

**Comment by willnet** [comment]
@nekoteni さん参加

**Comment by willnet** [comment]
店候補 [塚田農場 渋谷宮益坂店 宮崎県日南市(宮益坂/創作料理) | ホットペッパーグルメ](http://www.hotpepper.jp/strJ001018936/)

**Comment by ginkouno** [comment]
予約取りました〜
http://www.hotpepper.jp/strJ001018936/
19:30 - 21:30 8名 コウノ で取ってあります。
よろしくお願いします！

**Comment by machida** [comment]
@ginkouno お店予約ありがとうございます！！

**Comment by willnet** [comment]
今日ですね！参加される方よろしくお願いしますー

@machida @is8r @champierre @bluerabbit @ginkouno

**Comment by willnet** [comment]
@komagata さんは来ないのかな

**Comment by ginkouno** [comment]
よろしくお願いします!!

**Comment by machida** [comment]
今仕事終わりました！水道橋から駆けつけます

**Comment by willnet** [comment]
楽しい新年会でした :beers:
