### ISSUE TITLE
【番外編】2016-05-10(Tue) esa.io 2周年記念パーティーやります (\\( ⁰⊖⁰)/) 

### ISSUE THREAD

**Issue by taea** [yurufuwa/meetups#72]
esa.io が誕生してから、おかげさまで2周年を迎えます(\( ⁰⊖⁰)/) 
部室でささやかでゆるいお祝いの会をしますので、よかったらお越しください！ 
ご飯とかお酒とかｱﾘﾏｽ :sake: :beer: :stew: :meat_on_bone: :birthday:

（※だいぶ狭いところで、基本飲んでるだけの会です:bow:）
## 日時

2016/05/10（火）17:00 〜 22:00
（時間は適当に来れるタイミングでお越しください）
## 場所

esa社オフィス（ﾌﾞｼﾂ）
〒150-0002 東京都渋谷区渋谷3-1-15 ゾンネンハイム渋谷404
[Google Map](https://www.google.co.jp/maps/place/%E3%80%92150-0002+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E6%B8%8B%E8%B0%B7%EF%BC%93%E4%B8%81%E7%9B%AE%EF%BC%91%E2%88%92%EF%BC%91%EF%BC%95/@35.6577529,139.7051201,17z/data=!4m13!1m7!3m6!1s0x60188b5c1d93e777:0x9b6bdcea191f023a!2z44CSMTUwLTAwMDIg5p2x5Lqs6YO95riL6LC35Yy65riL6LC377yT5LiB55uu77yR4oiS77yR77yV!3b1!8m2!3d35.6577529!4d139.7073088!3m4!1s0x60188b5c1d93e777:0x9b6bdcea191f023a!8m2!3d35.6577529!4d139.7073088)

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.780123793558!2d139.7051419652582!3d35.65778853019967!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b5c1d8d49d1%3A0x5e5e588f9d498bf5!2z44CSMTUwLTAwMDIg5p2x5Lqs6YO95riL6LC35Yy65riL6LC377yT5LiB55uu77yR4oiS77yR77yVIOOCvuODs-ODjeODs-ODj-OCpOODoOa4i-iwtw!5e0!3m2!1sja!2sjp!4v1462425137414" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

## 来て下さる方

このIssueにコメントいただくか、[esa_io (@esa_io) | Twitter](https://twitter.com/esa_io) にメンションください。

**Comment by fukayatsu** [comment]
=͟͟͞͞ (\( ⁰⊖⁰)/)

**Comment by taea** [comment]
──=≡=͟͟͞͞(\( ⁰⊖⁰)/)

**Comment by kazuoishigame** [comment]
────=≡=͟͟͞͞(( ⁰⊖⁰)/)

**Comment by willnet** [comment]
γ'"´｀"''ヽ
　　 　 　/ 　 ●　　ｌ
　　　　/⌒)　　Oo ミ
　　　　ヽｌ'l　 wwWW
　　　　　 ﾉ　　　　　ヽ
　　　　　ｌ　　,---　　ヽ
　　　　　ｌ　　ヽ)ヽヽヾヽ
　　　　　ヽ　　　ヽヽヾヽヽ
　　　　　　ヽ　　　ヽヾヽヽヽ
　　　　　　　ヽ　　　ヽヽヾヽヽ
　　　　　　　　ヽ　　　ヽヽヽ　三三三三三∑
　　　　　　　　　丶､＿ヽヾヽ
　　　　　　　　　　((((　))))

**Comment by hiroy** [comment]
疲れてなければ表参道から 💨

**Comment by kjirou** [comment]
祝うついでに本を返しに

**Comment by taea** [comment]
ありがとう〜 "(\( ⁰⊖⁰)/)"

**Comment by fukayatsu** [comment]
[diary/2016/05/12/esaが生誕2周年 - docs.esa.io](https://docs.esa.io/posts/189)
