### ISSUE TITLE
[雪なので来週にリスケ] 第82回 meetup 2018-01-22(Mon) 19:30 〜 @フィヨルド

### ISSUE THREAD

**Issue by machida** [yurufuwa/meetups#94]
雪なので来週にリスケしました。
https://github.com/yurufuwa/meetups/issues/95

この回は「無し」でお願いします。

---

日時: 2018-01-22(Mon) 19:30 〜 22:00
会場: フィヨルドオフィス
定員: 6名
参加費: なし (おやつやおつまみなどは歓迎 🍻 )

参加方法

この issue に以下の内容でコメントつけてください。
もしご都合が悪くなってしまった場合はその旨追記お願いします。
繰り上がりリマインダ等は送りませんので各自でご確認ください。

当日やりたいこと
何か一言
当日の流れ

19:30〜19:45 ゆるゆるっと集合
19:45〜 自己紹介とやりたいことを発表（夜ご飯を食べていくか、帰るか聞きます）
20:00〜 ゆるふわに開発、ご飯を食べていく人用のピザを注文
21:15〜 成果発表、次回の日付決める
22:00〜 片付け
22:00 夜ご飯を食べていく人は会場に残ってピザを食べます( ˘ω˘)"
会場

合同会社フィヨルドへの行き方

最寄り駅 京王新線初台駅（注: 京王線ではなく京王新線、快速でも停まります）
ドエルヤマト 203号室 を呼んでください
迷った場合などは #yurudev タグつけて町田 (@machida) までメンションください。

持ち物

PC
@ALL

**Comment by machida** [comment]
あけましておめでとうございます。今年最初のゆるでぶ、開催が遅れてすいません。
フィヨルドブートキャンプやります。

**Comment by taea** [comment]
ありがとうございます！
参加します(\\( ⁰⊖⁰)/) 

savanna.io やります

**Comment by machida** [comment]
@taea ピヨるど、フィヨルドブートキャンプで使わせていただきますー

![default](https://user-images.githubusercontent.com/168265/34974363-eac2860e-facf-11e7-91da-ed4d943ae1f3.png)

![image](https://user-images.githubusercontent.com/168265/34974353-dd5ffe4c-facf-11e7-8723-a0737a6eec33.png)

**Comment by taea** [comment]
@machida まじすか！！やった！www
かわいい！！特に下っ腹がイイ(ΦωΦ)

**Comment by itog** [comment]
突然ですが、行ってもいいですか？

**Comment by machida** [comment]
@itog

おおー、ご無沙汰してます！！
来てくださいー！！

**Comment by bluerabbit** [comment]
@itog に久しぶりに会うために行きます

**Comment by champierre** [comment]
いきます。20:00-21:00からリモートで打ち合わせなんですみっこの方にいていいですか？

**Comment by champierre** [comment]
雪が降りそうな場合、行けないと思います。

**Comment by bluerabbit** [comment]
雪が降りそうなので今日は辞退します 💦

**Comment by machida** [comment]
@taea @itog @bluerabbit @champierre @komagata 

今日が雪なので、来週にリスケしましたー！
https://github.com/yurufuwa/meetups/issues/95

今日は「無し」でお願いします 🙏
